[project]
name = "crawlevery"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "scrapy>=2.13.4",
    "scrapy-playwright>=0.0.44",
]
